import type { LibraryCapabilities, LibraryDefinition, LibraryId } from "../types";

export const STANDARD_LIBRARY_CAPABILITIES: LibraryCapabilities = {
  category: true,
  tags: true,
  search: true,
  favorite: true,
  rating: true,
  enableDisable: true,
  stats: true,
  dbIndex: true,
  resourceCount: true,
  updatedAt: true,
  thumbnail: true,
  preview: true,
  detail: true,
};

export const LIBRARY_DEFINITIONS: LibraryDefinition[] = [
  {
    id: "image",
    slug: "image-library",
    title: "Image Library",
    titleZh: "图片素材库",
    description: "AI 图片、摄影、插画、PNG、背景、纹理、封面、缩略图",
    storageDir: "image",
    categories: ["AI图片", "摄影图片", "插画", "PNG", "背景图", "纹理", "封面", "缩略图"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "assets",
      assetKinds: ["image", "thumbnail", "cover"],
      registrySlug: "image",
      countWhere: "kind IN ('image','thumbnail','cover') AND deleted_at IS NULL",
    },
  },
  {
    id: "video",
    slug: "video-library",
    title: "Video Library",
    titleZh: "视频素材库",
    description: "AI 视频、实拍、B-roll、绿幕、无人机、动画、循环视频",
    storageDir: "video",
    categories: ["AI视频", "实拍", "B-roll", "绿幕", "无人机", "动画", "循环视频"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "assets",
      assetKinds: ["video"],
      registrySlug: "video",
      countWhere: "kind = 'video' AND deleted_at IS NULL",
    },
  },
  {
    id: "music",
    slug: "music-library",
    title: "Music Library",
    titleZh: "音乐库",
    description: "BGM、电影配乐、电子、LoFi、古风、史诗、轻音乐、环境音乐",
    storageDir: "music",
    categories: ["BGM", "电影配乐", "电子", "LoFi", "古风", "史诗", "轻音乐", "环境音乐"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "music_library",
      secondaryTables: ["assets"],
      assetKinds: ["bgm", "audio"],
      registrySlug: "music",
    },
  },
  {
    id: "sfx",
    slug: "sfx-library",
    title: "SFX Library",
    titleZh: "音效库",
    description: "Whoosh、Click、Explosion、UI、环境音、动物、交通、自然",
    storageDir: "sfx",
    categories: ["Whoosh", "Click", "Explosion", "UI", "环境音", "动物", "交通", "自然"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "assets",
      assetKinds: ["sfx", "audio"],
      registrySlug: "sfx",
      countWhere: "kind IN ('sfx','audio') AND deleted_at IS NULL",
    },
  },
  {
    id: "voice",
    slug: "voice-library",
    title: "Voice Library",
    titleZh: "配音库",
    description: "Fish Speech、F5-TTS、CosyVoice、Edge TTS、OpenAI TTS、ElevenLabs 及全部音色",
    storageDir: "voice",
    categories: [
      "Fish Speech",
      "F5-TTS",
      "CosyVoice",
      "Edge TTS",
      "OpenAI TTS",
      "ElevenLabs",
      "音色预设",
    ],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "voice_library",
      secondaryTables: ["assets"],
      registrySlug: "voice",
    },
  },
  {
    id: "subtitle",
    slug: "subtitle-library",
    title: "Subtitle Library",
    titleZh: "字幕模板库",
    description: "ASS 模板、SRT 模板、字幕样式、字体、字幕动画、字幕预设",
    storageDir: "subtitle",
    categories: ["ASS模板", "SRT模板", "字幕样式", "字体", "字幕动画", "字幕预设"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "subtitle_library",
      secondaryTables: ["templates", "assets"],
      templateKind: "subtitle",
      assetKinds: ["subtitle"],
      registrySlug: "subtitle",
    },
  },
  {
    id: "effect",
    slug: "effect-library",
    title: "Effect Library",
    titleZh: "特效模板库",
    description: "OpenCut 特效、FFmpeg 特效、滤镜、转场、LUT、粒子、光效",
    storageDir: "effect",
    categories: ["OpenCut特效", "FFmpeg特效", "滤镜", "转场", "LUT", "粒子", "光效"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "effects_library",
      secondaryTables: ["templates"],
      templateKind: "effect",
      registrySlug: "effect",
    },
  },
  {
    id: "prompt",
    slug: "prompt-library",
    title: "Prompt Library",
    titleZh: "Prompt 与知识库",
    description: "Prompt、脚本模板、分镜模板、提示词、AI 知识、最佳实践、工作流模板",
    storageDir: "prompt",
    categories: [
      "Prompt",
      "脚本模板",
      "分镜模板",
      "提示词",
      "AI知识",
      "最佳实践",
      "工作流模板",
    ],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "prompts",
      secondaryTables: ["templates", "materials"],
      templateKind: "prompt",
      registrySlug: "prompt",
    },
  },
  {
    id: "character",
    slug: "character-library",
    title: "Character Library",
    titleZh: "人物角色库",
    description: "角色、人物设定、服装、发型、年龄、身份、IP 角色、一致性角色",
    storageDir: "character",
    categories: ["角色", "人物设定", "服装", "发型", "年龄", "身份", "IP角色", "一致性角色"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "characters",
      secondaryTables: ["assets", "resource_registry"],
      registrySlug: "character",
      countWhere: "deleted_at IS NULL",
    },
  },
  {
    id: "lora",
    slug: "lora-library",
    title: "LoRA Library",
    titleZh: "LoRA 模型库",
    description: "Flux、SDXL、ComfyUI、LoRA、ControlNet、Embedding、风格模型",
    storageDir: "lora",
    categories: ["Flux", "SDXL", "ComfyUI", "LoRA", "ControlNet", "Embedding", "风格模型"],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "templates",
      templateKind: "lora",
      registrySlug: "lora",
      countWhere: "template_kind = 'lora'",
    },
  },
  {
    id: "dataset",
    slug: "dataset-library",
    title: "Dataset Library",
    titleZh: "数据集与训练库",
    description: "训练数据、图片/视频/文本数据集、标注数据、模型训练数据、RAG 知识库",
    storageDir: "dataset",
    categories: [
      "训练数据",
      "图片数据集",
      "视频数据集",
      "文本数据集",
      "标注数据",
      "模型训练数据",
      "RAG知识库",
    ],
    capabilities: STANDARD_LIBRARY_CAPABILITIES,
    dbMapping: {
      primaryTable: "glossaries",
      secondaryTables: ["glossary_entries", "assets", "materials"],
      registrySlug: "dataset",
    },
  },
];

export const LIBRARY_BY_ID: Record<LibraryId, LibraryDefinition> = Object.fromEntries(
  LIBRARY_DEFINITIONS.map((d) => [d.id, d])
) as Record<LibraryId, LibraryDefinition>;

export const LIBRARY_IDS: LibraryId[] = LIBRARY_DEFINITIONS.map((d) => d.id);
